### PR TITLE
docs(comment): add channelOwner field

### PR DESCRIPTION
**Pull request by FineFindus**
Adds the `channelOwner` field added in https://github.com/TeamPiped/Piped-Backend/pull/727.

### CODE REVIEW

**Comment by FireMasterK** [comment]
We should also add these fields to https://github.com/TeamPiped/OpenAPI, I want to remove most of the markdown based documentation to something based on OpenAPI like Redoc or Swagger.

**Comment by FineFindus** [comment]
Awesome! I'm not familiar with OpenAPI, but would it be possible to generate the docs based on the (currently non-existent) documentation in the code? I think that would be preferable to keeping them in sync manually.

**Comment by FireMasterK** [comment]
> Awesome! I'm not familiar with OpenAPI, but would it be possible to generate the docs based on the (currently non-existent) documentation in the code? I think that would be preferable to keeping them in sync manually.

We can't generate documentation directly from the code afaik. Maybe we can create a PR template with a checklist in case someone adds a new field to the backend?

I've added a lot of documentation to the OpenAPI spec that the backend currently lacks. You could have a look at:

Redoc: https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/TeamPiped/OpenAPI/main/swagger.yaml

Swagger: visit https://petstore.swagger.io/ and enter https://raw.githubusercontent.com/TeamPiped/OpenAPI/main/swagger.yaml, and finally click explore.

**Comment by FineFindus** [comment]
> We can't generate documentation directly from the code afaik. Maybe we can create a PR template with a checklist in case someone adds a new field to the backend?

Sounds great. Maybe the API docs could also be moved into this repo? That would reduce the effort to incorporate it in future PRs, as it's easier to simply edit a single file and push, then to also create a complete PR for it as well.

**Pull request closed without merging**
